### PR TITLE
Allow time_window / chunk_size change without reset

### PR DESCRIPTION
**Pull request by stevenabreu7**
I want to read a file chunked into time windows, and discard the first `T` time steps. This is currently not always possible because when changing the window/chunk size, the wizard is reset. So I would suggest adding a flag `do_reset` to the `change_time_window` and `change_chunk_size` method (which defaults to True, the current behavior).

### CODE REVIEW

**Comment by stevenabreu7** [comment]
I would further suggest to use `µs` instead of `ms` everywhere, for consistency (→ `Wizard.read_time_window`), but this can also be a separate PR if you prefer

**Comment by fabrizio-ottati** [comment]
Nice :) 

For what concerns microseconds, sure! We just need to update also the C code in which the milliseconds are changed to microseconds! Feel free of doing that in this PR, it's really fast to do

**Comment by stevenabreu7** [comment]
Should be good now?

**Comment by fabrizio-ottati** [comment]
Fantastic! Thank you @stevenabreu7!

**Pull request merged**
